name: tests
on:
  push:
    branches: ['main']
    paths-ignore:
      - "docs/*"
      - "**.md"
  pull_request:
    paths-ignore:
      - "docs/*"
      - "**.md"
permissions: read-all
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.27']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        persist-credentials: false
    - name: Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
    - name: Test
      run: go test -race -timeout 40m ./...
  test-freebsd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        persist-credentials: false
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@4469451fe39bee80be4066836c5170362e9349f3
      with:
        usesh: true
        prepare: |
        run: |
          pkg update -f
          pkg install -y git wget gnupg

          wget https://go.dev/dl/go1.27.0.freebsd-amd64.tar.gz
          tar -C /usr/local -xzf go1.27.0.freebsd-amd64.tar.gz

          /usr/local/go/bin/go test -race -timeout 40m ./...
